# Generated by Django 4.0.4 on 2022-05-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='date_creation',
            field=models.DateField(auto_now=True),
        ),
    ]
