# Generated by Django 4.0.4 on 2022-05-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0002_memoire_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='nom',
            new_name='nom_ens',
        ),
        migrations.RenameField(
            model_name='enseignant',
            old_name='prenom',
            new_name='prenom_ens',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='nom',
            new_name='nom_ent',
        ),
        migrations.RenameField(
            model_name='soutenance',
            old_name='mention',
            new_name='mention_sout',
        ),
    ]
