# Generated by Django 4.0.4 on 2022-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0003_rename_nom_enseignant_nom_ens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soutenance',
            old_name='date',
            new_name='date_sout',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='type',
            new_name='type_stage',
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='nom',
        ),
        migrations.AddField(
            model_name='parcours',
            name='parcours',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='memoire',
            field=models.FileField(upload_to='document/%Y/%m/%d/'),
        ),
    ]
