# Generated by Django 4.0.4 on 2022-05-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0004_rename_date_soutenance_date_sout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mention',
            old_name='nom',
            new_name='mention',
        ),
    ]
