# Generated by Django 4.0.4 on 2022-05-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0006_soutenance_type_sout_alter_parcours_parcours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soutenance',
            old_name='type_sout',
            new_name='sout',
        ),
    ]
