# Generated by Django 4.0.4 on 2022-05-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0007_rename_type_sout_soutenance_sout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='sout',
        ),
    ]
