# Generated by Django 4.0.4 on 2022-05-21 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0008_remove_soutenance_sout'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='type_sout',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
