# Generated by Django 4.0.4 on 2022-05-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0010_alter_memoire_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='resume',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='type_sout',
            field=models.CharField(max_length=255),
        ),
    ]
