# Generated by Django 4.0.4 on 2022-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0011_alter_memoire_resume_alter_soutenance_type_sout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memoire',
            old_name='memoire',
            new_name='memoire_doc',
        ),
        migrations.AlterField(
            model_name='memoire',
            name='resume',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='type_sout',
            field=models.CharField(max_length=20),
        ),
    ]
