# Generated by Django 4.0.4 on 2022-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0012_rename_memoire_memoire_memoire_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='date_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
