# Generated by Django 4.0.4 on 2022-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0013_alter_memoire_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='memoire_doc',
            field=models.FileField(blank=True, upload_to='document/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='resume',
            field=models.TextField(),
        ),
    ]
