# Generated by Django 4.0.4 on 2022-06-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0014_alter_memoire_memoire_doc_alter_memoire_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='type_sout',
        ),
    ]
