# Generated by Django 4.0.4 on 2022-06-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0015_remove_soutenance_type_sout'),
    ]

    operations = [
        migrations.CreateModel(
            name='encadreur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('memoire.enseignant',),
        ),
        migrations.CreateModel(
            name='examinateur',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('memoire.enseignant',),
        ),
        migrations.CreateModel(
            name='president',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('memoire.enseignant',),
        ),
        migrations.CreateModel(
            name='jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encadreur', to='memoire.encadreur')),
                ('examinateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinateur', to='memoire.examinateur')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='memoire.president')),
            ],
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='jury',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.jury'),
        ),
    ]
