# Generated by Django 4.0.4 on 2022-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0018_alter_mention_mention_alter_parcours_parcours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='mention_sout',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Tres Bien', 'Tres Bien'), ('Bien', 'Bien'), ('Assez Bien', 'Assez Bien')], max_length=20),
        ),
    ]
