# Generated by Django 4.0.4 on 2022-06-16 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0019_alter_soutenance_mention_sout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='enseignant',
        ),
    ]
