# Generated by Django 4.0.4 on 2022-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0020_remove_etudiant_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='annee_academique',
            field=models.CharField(max_length=100),
        ),
    ]
