# Generated by Django 4.0.4 on 2022-06-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0021_alter_memoire_annee_academique'),
    ]

    operations = [
        migrations.CreateModel(
            name='annee_academique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='memoire',
            name='annee_academique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoire.annee_academique'),
        ),
    ]
