# Generated by Django 4.0.4 on 2022-06-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0024_alter_annee_academique_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annee_academique',
            name='annee',
            field=models.DateField(unique=True),
        ),
    ]
