# Generated by Django 4.0.4 on 2022-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0025_alter_annee_academique_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('Maitre de conference', 'Maitre de conference'), ('Chargé de cours', 'chargé de cours'), ('Assistant', 'Assistant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom_ens',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
