# Generated by Django 4.0.4 on 2022-07-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0026_alter_enseignant_grade_alter_enseignant_prenom_ens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='mention_sout',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Tres Bien', 'Tres Bien'), ('Bien', 'Bien'), ('Assez Bien', 'Assez Bien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='note',
            field=models.FloatField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='salle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
