# Generated by Django 4.0.4 on 2022-07-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0027_alter_soutenance_mention_sout_alter_soutenance_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('Maitre de conference', 'Maitre de conference'), ('Chargé de cours', 'chargé de cours'), ('Assistant(e)', 'Assistant(e)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom_ens',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom_ens',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='note',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
