# Generated by Django 4.0.4 on 2022-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0028_alter_enseignant_grade_alter_enseignant_nom_ens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoire',
            name='mot_cle',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='titre',
            field=models.CharField(max_length=1000),
        ),
    ]
