# Generated by Django 4.0.4 on 2022-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0029_alter_memoire_mot_cle_alter_memoire_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='lieu',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom_ent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jury',
            name='encadreur_ind',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='parcours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='mention_sout',
            field=models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Tres Bien', 'Tres Bien'), ('Bien', 'Bien'), ('Assez Bien', 'Assez Bien')], max_length=100),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='salle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='type_stage',
            field=models.CharField(max_length=100),
        ),
    ]
