# Generated by Django 4.0.4 on 2022-07-06 21:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('memoire', '0030_alter_entreprise_lieu_alter_entreprise_nom_ent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
