# Generated by Django 4.0.4 on 2022-07-06 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memoire', '0031_memoire_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
