# Generated by Django 4.0.4 on 2022-07-11 09:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('memoire', '0032_memoire_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoire',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='mot_cle',
        ),
        migrations.AddField(
            model_name='memoire',
            name='mot_cle',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
