# Generated by Django 4.0.4 on 2022-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0017_projection_cellule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='arrondissement',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
