# Generated by Django 4.0.4 on 2022-07-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0018_alter_contribuable_arrondissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='arrondissement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
