# Generated by Django 4.0.4 on 2022-07-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0019_alter_contribuable_arrondissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuable',
            name='activite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='raison_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contribuable',
            name='telephone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone'),
        ),
    ]
