# Generated by Django 4.0.4 on 2022-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_cime', '0020_alter_contribuable_activite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part_impot',
            options={'verbose_name': 'Repartition Impot'},
        ),
        migrations.AlterModelOptions(
            name='regime_impot',
            options={'verbose_name': "Régime d'imposition"},
        ),
        migrations.AlterModelOptions(
            name='sous_secteur',
            options={'verbose_name': 'Sous secteur'},
        ),
        migrations.AlterModelOptions(
            name='ug',
            options={'verbose_name': 'Unité de gestion'},
        ),
        migrations.AlterField(
            model_name='declaration',
            name='num_avis',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='impot_amr',
            name='montant',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='impot_amr',
            name='montant_budg',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='impot_declare',
            name='montant',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payement',
            name='montant',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payement',
            name='num_avis',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projection',
            name='montant',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projection_impot',
            name='montant',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ug',
            name='ug',
            field=models.PositiveIntegerField(verbose_name='N° UG'),
        ),
    ]
